# Generated by Django 5.0.2 on 2024-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agedistribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age_group', models.CharField(blank=True, max_length=21, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('age_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agedistribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monthlydistribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthlydistribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policestdistribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_id', models.CharField(blank=True, max_length=15, null=True)),
                ('police_station', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policestdistribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yearlydistribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yearlydistribution',
                'managed': False,
            },
        ),
    ]
