# Generated by Django 5.0.2 on 2024-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unidentifieddeadbodies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('natural_no_of_cases', models.IntegerField(blank=True, null=True)),
                ('unnatural_no_of_cases', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidentifieddeadbodies',
                'managed': False,
            },
        ),
    ]
